version: 2.1

jobs:
  build_docs:
    docker:
      - image: cimg/python:3.7.13-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docs-requirements
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install -e .
      - save_cache:
          paths:
            - /home/circleci/.cache/pip/
          key: v1-docs-requirements
      - run:
          name: Build docs
          command: |
            	jupyter-book clean -a docs
	            jupyter-book build docs/source --path-output docs
	            jupyter-book build docs/source --path-output docs --builder linkcheck

workflows:
  main:
    jobs:
      - build_docs
